# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab_2_2/Lab_2_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_2 || ORIG_REF_NAME==Lab_2_2} -quiet] -quiet

# IP: bd/Lab_2_2/ip/Lab_2_2_processing_system7_0_0/Lab_2_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_2_processing_system7_0_0 || ORIG_REF_NAME==Lab_2_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab_2_2/ip/Lab_2_2_axi_gpio_0_1/Lab_2_2_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_2_axi_gpio_0_1 || ORIG_REF_NAME==Lab_2_2_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Lab_2_2/ip/Lab_2_2_xbar_0/Lab_2_2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_2_xbar_0 || ORIG_REF_NAME==Lab_2_2_xbar_0} -quiet] -quiet

# IP: bd/Lab_2_2/ip/Lab_2_2_auto_pc_0/Lab_2_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_2_auto_pc_0 || ORIG_REF_NAME==Lab_2_2_auto_pc_0} -quiet] -quiet

# IP: bd/Lab_2_2/ip/Lab_2_2_auto_cc_0/Lab_2_2_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_2_auto_cc_0 || ORIG_REF_NAME==Lab_2_2_auto_cc_0} -quiet] -quiet

# IP: bd/Lab_2_2/ip/Lab_2_2_ps7_0_axi_periph_2/Lab_2_2_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_2_ps7_0_axi_periph_2 || ORIG_REF_NAME==Lab_2_2_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/Lab_2_2/ip/Lab_2_2_rst_ps7_0_100M_2/Lab_2_2_rst_ps7_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_2_rst_ps7_0_100M_2 || ORIG_REF_NAME==Lab_2_2_rst_ps7_0_100M_2} -quiet] -quiet

# IP: bd/Lab_2_2/ip/Lab_2_2_PmodAD1_0_3/Lab_2_2_PmodAD1_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_2_PmodAD1_0_3 || ORIG_REF_NAME==Lab_2_2_PmodAD1_0_3} -quiet] -quiet

# IP: bd/Lab_2_2/ip/Lab_2_2_rst_ps7_0_50M_0/Lab_2_2_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_2_rst_ps7_0_50M_0 || ORIG_REF_NAME==Lab_2_2_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/Lab_2_2/Lab_2_2_ooc.xdc
