# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Zynq_Book/TC_PmodAD1/TC_PmodAD1.srcs/sources_1/bd/Lab_2_2/ip/Lab_2_2_axi_gpio_0_1/Lab_2_2_axi_gpio_0_1.xci
# IP: The module: 'Lab_2_2_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/TC_PmodAD1/TC_PmodAD1.srcs/sources_1/bd/Lab_2_2/ip/Lab_2_2_axi_gpio_0_1/Lab_2_2_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/TC_PmodAD1/TC_PmodAD1.srcs/sources_1/bd/Lab_2_2/ip/Lab_2_2_axi_gpio_0_1/Lab_2_2_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/TC_PmodAD1/TC_PmodAD1.srcs/sources_1/bd/Lab_2_2/ip/Lab_2_2_axi_gpio_0_1/Lab_2_2_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Zynq_Book/TC_PmodAD1/TC_PmodAD1.srcs/sources_1/bd/Lab_2_2/ip/Lab_2_2_axi_gpio_0_1/Lab_2_2_axi_gpio_0_1.xci
# IP: The module: 'Lab_2_2_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/TC_PmodAD1/TC_PmodAD1.srcs/sources_1/bd/Lab_2_2/ip/Lab_2_2_axi_gpio_0_1/Lab_2_2_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/TC_PmodAD1/TC_PmodAD1.srcs/sources_1/bd/Lab_2_2/ip/Lab_2_2_axi_gpio_0_1/Lab_2_2_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/TC_PmodAD1/TC_PmodAD1.srcs/sources_1/bd/Lab_2_2/ip/Lab_2_2_axi_gpio_0_1/Lab_2_2_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
